//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityEditorSelecter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityEditorSelecter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Hierarchy_checkbox {
            get {
                object obj = ResourceManager.GetObject("Hierarchy_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Hierarchy_sima {
            get {
                object obj = ResourceManager.GetObject("Hierarchy_sima", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   using System.Linq;
        ///using UnityEngine;
        ///using UnityEditor;
        ///
        ///public static class HierarchyChangeColorEditor
        ///{
        ///	// 横幅
        ///	private const int width = 16;
        ///
        ///
        ///	[InitializeOnLoadMethod]
        ///	private static void HierarchyChangeColor()
        ///	{
        ///		EditorApplication.hierarchyWindowItemOnGUI += changeGUI;
        ///	}
        ///
        ///	private static void changeGUI(int instanceId, Rect selectionRect)
        ///	{
        ///		//=============================================
        ///		// 一行おきに色を変えてHierarchyを見やすくする
        ///		//=============================================
        ///		var  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HierarchyChangeColorEditor {
            get {
                return ResourceManager.GetString("HierarchyChangeColorEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using System.Linq;
        ///using UnityEngine;
        ///using UnityEditor;
        ///
        ///public static class HierarchyCheckBoxEditor
        ///{
        ///	// 横幅
        ///	private const int width = 16;
        ///
        ///
        ///	[InitializeOnLoadMethod]
        ///	private static void HierarchyCheckBoxEditor()
        ///	{
        ///		EditorApplication.hierarchyWindowItemOnGUI += setActiveBoxView;
        ///	}
        ///
        ///	private static void setActiveBoxView(int instanceId, Rect selectionRect)
        ///	{
        ///		//=============================================
        ///		// SetActive
        ///		// チェックボックスを表示
        ///		//====================================== [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HierarchyCheckBoxEditor {
            get {
                return ResourceManager.GetString("HierarchyCheckBoxEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string image1 {
            get {
                return ResourceManager.GetString("image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Tool_shortcut {
            get {
                object obj = ResourceManager.GetObject("Tool_shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
